// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"api-service-template/internal/app/adapter"
	"api-service-template/internal/app/command"
	"api-service-template/internal/app/service"
	"api-service-template/internal/infra"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitDBRepository(db *gorm.DB) *Repositories {
	userDBRepository := infra.NewUserDBRepository(db)
	administratorDBRepository := infra.NewAdministratorDBRepository(db)
	repositories := &Repositories{
		User:          userDBRepository,
		Administrator: administratorDBRepository,
	}
	return repositories
}

func InitCommands(db *gorm.DB) *Commands {
	userDBRepository := infra.NewUserDBRepository(db)
	userService := service.UserService{
		User: userDBRepository,
	}
	createUserHandler := &command.CreateUserHandler{
		User:      userDBRepository,
		CheckUser: userService,
	}
	deleteUserHandler := &command.DeleteUserHandler{
		User: userDBRepository,
	}
	updateUserHandler := &command.UpdateUserHandler{
		User: userDBRepository,
	}
	findUserHandler := &command.FindUserHandler{
		User: userDBRepository,
	}
	listUserHandler := &command.ListUserHandler{
		User: userDBRepository,
	}
	administratorDBRepository := infra.NewAdministratorDBRepository(db)
	createAdministratorHandler := &command.CreateAdministratorHandler{
		Administrator: administratorDBRepository,
	}
	deleteAdministratorHandler := &command.DeleteAdministratorHandler{
		Administrator: administratorDBRepository,
	}
	updateAdministratorHandler := &command.UpdateAdministratorHandler{
		Administrator: administratorDBRepository,
	}
	findAdministratorHandler := &command.FindAdministratorHandler{
		Administrator: administratorDBRepository,
	}
	listAdministratorHandler := &command.ListAdministratorHandler{
		Administrator: administratorDBRepository,
	}
	commands := &Commands{
		CreateUser:          createUserHandler,
		DeleteUser:          deleteUserHandler,
		UpdateUser:          updateUserHandler,
		FindUser:            findUserHandler,
		ListUser:            listUserHandler,
		CreateAdministrator: createAdministratorHandler,
		DeleteAdministrator: deleteAdministratorHandler,
		UpdateAdministrator: updateAdministratorHandler,
		FindAdministrator:   findAdministratorHandler,
		ListAdministrator:   listAdministratorHandler,
	}
	return commands
}

// wire.go:

var (
	dbRepositorySet = wire.NewSet(wire.NewSet(infra.NewUserDBRepository, wire.Bind(new(adapter.UserRepository), new(*infra.UserDBRepository)), infra.NewAdministratorDBRepository, wire.Bind(new(adapter.AdministratorRepository), new(*infra.AdministratorDBRepository))),
	)

	serviceSet = wire.NewSet(wire.Struct(new(service.UserService), "*"))

	dbRepositoryProvider = wire.NewSet(
		dbRepositorySet, wire.Struct(new(Repositories), "*"),
	)

	commandsProvider = wire.NewSet(
		serviceSet,
		dbRepositorySet, wire.Struct(new(command.CreateUserHandler), "*"), wire.Struct(new(command.DeleteUserHandler), "*"), wire.Struct(new(command.UpdateUserHandler), "*"), wire.Struct(new(command.FindUserHandler), "*"), wire.Struct(new(command.ListUserHandler), "*"), wire.Struct(new(command.CreateAdministratorHandler), "*"), wire.Struct(new(command.DeleteAdministratorHandler), "*"), wire.Struct(new(command.UpdateAdministratorHandler), "*"), wire.Struct(new(command.FindAdministratorHandler), "*"), wire.Struct(new(command.ListAdministratorHandler), "*"), wire.Struct(new(Commands), "*"),
	)
)
