// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"api-service-template/internal/app/adapter"
	"api-service-template/internal/app/command"
	"api-service-template/internal/app/service"
	"api-service-template/internal/infra"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitDBRepository(db *gorm.DB) *Repositories {
	userDBRepository := infra.NewUserDBRepository(db)
	repositories := &Repositories{
		User: userDBRepository,
	}
	return repositories
}

func InitCommands(db *gorm.DB) *Commands {
	userDBRepository := infra.NewUserDBRepository(db)
	userService := service.UserService{
		User: userDBRepository,
	}
	createUserHandler := &command.CreateUserHandler{
		User:      userDBRepository,
		CheckUser: userService,
	}
	updateUserHandler := &command.UpdateUserHandler{
		User: userDBRepository,
	}
	commands := &Commands{
		CreateUser: createUserHandler,
		UpdateUser: updateUserHandler,
	}
	return commands
}

// wire.go:

var (
	dbRepositorySet = wire.NewSet(wire.NewSet(infra.NewUserDBRepository, wire.Bind(new(adapter.UserRepository), new(*infra.UserDBRepository))),
	)

	serviceSet = wire.NewSet(wire.Struct(new(service.UserService), "*"))

	dbRepositoryProvider = wire.NewSet(
		dbRepositorySet, wire.Struct(new(Repositories), "*"),
	)

	commandsProvider = wire.NewSet(
		serviceSet,
		dbRepositorySet, wire.Struct(new(command.CreateUserHandler), "*"), wire.Struct(new(command.UpdateUserHandler), "*"), wire.Struct(new(Commands), "*"),
	)
)
